language: php
os: linux

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

jobs:
    allow_failures:
        - php: '7.4'

install:
    - composer install

script:
    - |
      composer run-script format || exit_code=$?
      if (( exit_code > 1 )) ; then
          exit $exit_code
      fi
    - composer test
